### ISSUE TITLE
React example not working?

### ISSUE THREAD

**Issue by vobenirod** [IBM/gantt-chart#6]
I stumbled upon this library and I'm trying to get the react demo working.
When I run the example on codesandbox I get the following error: 
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

Any idea what the issue is? 
I've attached the sandbox: https://codesandbox.io/s/flamboyant-poitras-uzxmq

**Comment by gillesdandrea** [comment]
Hello,

Example is misleading because it does rely on index.js that export 2
elements: GanttChart and version of the lib.

So basically, you have to:
import { GanttChart } from "ibm-gantt-chart-react";

I also added
import "./styles.css";

And added some css to use the full height:
html,
body,
body > div,
.App,
.ibm-gantt-chart-react {
height: 100%;
}
Not very elegant, but it works...

Regards,

Gilles.

**Comment by gillesdandrea** [comment]
Hello,

Example is misleading because it does rely on `index.js` that export 2
elements: GanttChart and version of the lib.

So basically, you have to:
`import { GanttChart } from "ibm-gantt-chart-react";`

I also added to your sandbox:
`import "./styles.css";`

And added some css to use the full height:
```
html,
body,
body > div,
.App,
.ibm-gantt-chart-react {
height: 100%;
}
```
Not very elegant, but it does the job...

**Comment by vobenirod** [comment]
Thanks @gillesdandrea  that seems to work but there appears to be one glitch.
I can see in the chart that there is a few numbers appearing randomly. ![](https://i.imgur.com/nHuo55D.png).

Also one more question as I cannot see in the documentation and do not want to spam with a new issue, is there a way to trigger an alert on click of an empty spot in a row?

**Comment by gillesdandrea** [comment]
1/ I create https://github.com/IBM/gantt-chart/issues/7 in order to track the misplaced row numbers that you highlighted.
2/ I'm not sure that a listener on empty spot are possible yet. I'm going to investigate.
